[2023-10-05T14:01:20.581+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info manual__2023-10-05T14:01:19.140352+00:00 [queued]>
[2023-10-05T14:01:20.593+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: elastic_dag.print_es_info manual__2023-10-05T14:01:19.140352+00:00 [queued]>
[2023-10-05T14:01:20.594+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T14:01:20.595+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-10-05T14:01:20.596+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-10-05T14:01:20.615+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_es_info> on 2023-10-05 14:01:19.140352+00:00
[2023-10-05T14:01:20.622+0000] {standard_task_runner.py:55} INFO - Started process 1336 to run task
[2023-10-05T14:01:20.625+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'elastic_dag', 'print_es_info', 'manual__2023-10-05T14:01:19.140352+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/elastic_dag.py', '--cfg-path', '/tmp/tmp6kkm25o3']
[2023-10-05T14:01:20.627+0000] {standard_task_runner.py:83} INFO - Job 94: Subtask print_es_info
[2023-10-05T14:01:20.687+0000] {task_command.py:376} INFO - Running <TaskInstance: elastic_dag.print_es_info manual__2023-10-05T14:01:19.140352+00:00 [running]> on host f3c0982b8122
[2023-10-05T14:01:20.764+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_dag
AIRFLOW_CTX_TASK_ID=print_es_info
AIRFLOW_CTX_EXECUTION_DATE=2023-10-05T14:01:19.140352+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-05T14:01:19.140352+00:00
[2023-10-05T14:01:20.766+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/elastic_dag.py", line 9, in _print_es_info
    print(hook.info())
  File "/opt/airflow/plugins/hooks/elastic/elastic_hook.py", line 26, in info
    return self.es.info() # return the info of the Elasticsearch cluster instance
AttributeError: 'ElasticHook' object has no attribute 'es'
[2023-10-05T14:01:20.819+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=elastic_dag, task_id=print_es_info, execution_date=20231005T140119, start_date=20231005T140120, end_date=20231005T140120
[2023-10-05T14:01:20.831+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 94 for task print_es_info ('ElasticHook' object has no attribute 'es'; 1336)
[2023-10-05T14:01:20.839+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-10-05T14:01:20.858+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
